# <--- Dont change version below --->
version = 1
# Champions Client

# Champions color (Hex)
hex_tier_1 = #FFFF55
hex_tier_2 = #F57C2C
hex_tier_3 = #46DFFA
hex_tier_4 = #8823DB
hex_tier_5 = #F98AFF

# Champions HUD position
y_offset_stars = -5
y_offset_text = 7
y_offset_bar = 19
y_offset_affixes = 29

x_offset_stars = 0
x_offset_text = 0
x_offset_bar = 0
x_offset_affixes = 0

# Will champions render through walls when cache_server has champions?
always_render = false

# Time cache for champions (millis) (max = 32767)
cache_client = 1000
cache_server = 5000
# If true, it will be render only when looking at the champion
only_for_view = false

