# <--- Dont change version below --->
version = 5
# Champions Server

# Tier 0 (not champion)
tier0_weight = 9460

# Tier 1
tier1_affixes_count = 1
tier1_weight = 400
tier1_growth_health = 1.5
tier1_growth_strength = 1.5

# Tier 2
tier2_affixes_count = 2
tier2_weight = 150
tier2_growth_health = 2.5
tier2_growth_strength = 1.8

# Tier 3
tier3_affixes_count = 3
tier3_weight = 32
tier3_growth_health = 4.0
tier3_growth_strength = 2.2

# Tier 4
tier4_affixes_count = 4
tier4_weight = 6
tier4_growth_health = 7.0
tier4_growth_strength = 3.5

# Tier 5
tier5_affixes_count = 8
tier5_weight = 2
tier5_growth_health = 12.0
tier5_growth_strength = 5.0

# Maximum tier for bosses (Wither, Ender Dragon)
max_boss_tier = 0

