# <--- Dont change version below --->
version = 2
# Champions Affixes

# Registry
# If true, the affix will be in the pool
hasty_affix = true
arctic_affix = true
molten_affix = true
desecrating_affix = true
plagued_affix = true
infected_affix = true
adaptive_affix = true
knocking_affix = true
shielding_affix = true
reflective_affix = true
magnetic_affix = true
dampening_affix = true
lively_affix = true
blinded_affix = true
paralyzing_affix = true

# Arctic
# Cooldown between arctic bullets (ticks)
cooldown_arctic = 160
# Molten
# Cooldown between molten bullets (ticks)
cooldown_molten = 90

# Desecrating
# Ticks between desecrating clouds
time_before_desecrating = 1000
# Duration of the cloud (ticks)
cloud_desecrating_duration = 200

# Plagued
# Duration of poison effect (ticks)
plagued_poison_duration = 200
# Poison amplifier
plagued_poison_amplifier = 0

# Infected
# Ticks between spawning silverfish
time_before_infecting = 600
# Max silverfish that can exist around champion
max_silverfish_count = 10
# Base number of silverfish to spawn
infected_silverfish = 4
# Additional silverfish (health * factor)
infected_factor_health = 0

# Reflective
# Damage reflected back to the attacker
reflection_damage = 2

# Healing
# Amount of heal
entity_heal = 1
# Amount of heal when champions doesn't have target
entity_heal_no_target = 4
# Ticks between healing
when_entity_heal = 20

# Knocking
knocking_strength = 1.5

# Magnetic
# Cooldown duration (ticks)
magnetic_cooldown = 600
# Pull time (ticks)
magnetic_pull_time = 150
# Pull strength
magnetic_strength = 1

# Hasty
# Speed effect amplifier
hasty_amplifier = 4

# Damage reduction multiplier (0.5 = 50% less damage taken)
dampening_amount = 0.5

# Shield
# Cycle time of the shield (ticks)
shield_all_time = 300
# How long the shield stays active (ticks)
shield_working_time = 60

# Blinded
# Chance to blind (1.0 - 0)
blind_chance = 0.2
# Blind effect duration (ticks)
blind_duration = 80

# Paralyzing
# Chance to paralyze (1.0 - 0)
paralyzing_chance = 0.1
# Paralyze effect duration (ticks)
paralyzing_duration = 60

